# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(name: '梁超',email: 'liangchaob@dcits.com',code: 'liangchaob',is_admin: true,password: 'P@ssw0rd',password_resetting: false)
# User.create(name: '鲁志梅',email: 'luzm@dcits.com',code: 'luzm',is_admin: true,password: 'P@ssw0rd',password_resetting: false)


# 团队导入

Team.create(name: "大客户Bu.北方区事业部",team_type: "none_tech")
Team.create(name: "大客户Bu.华南区事业部",team_type: "none_tech")
Team.create(name: "大客户Bu.新业务事业部",team_type: "none_tech")
Team.create(name: "大客户Bu.中南区事业部",team_type: "none_tech")
Team.create(name: "大客户Bu.中央区事业部",team_type: "none_tech")
Team.create(name: "大客户Bu.综合管理部",team_type: "none_tech")
Team.create(name: "第二金融Bu.金融核心客户事业部",team_type: "none_tech")
Team.create(name: "第二金融Bu.金融南区事业部",team_type: "none_tech")
Team.create(name: "第二金融Bu.金融业务拓展事业二部",team_type: "none_tech")
Team.create(name: "第二金融Bu.金融业务拓展事业三部",team_type: "none_tech")
Team.create(name: "第二金融Bu.金融业务拓展事业一部",team_type: "none_tech")
Team.create(name: "第二政企Bu.电力北区业务二部",team_type: "none_tech")
Team.create(name: "第二政企Bu.电力北区业务一部",team_type: "none_tech")
Team.create(name: "第二政企Bu.电力华东业务部",team_type: "none_tech")
Team.create(name: "第二政企Bu.电力南区事业部",team_type: "none_tech")
Team.create(name: "第二政企Bu.金融系统及安全事业部",team_type: "none_tech")
Team.create(name: "第二政企Bu.能源业务部",team_type: "none_tech")
Team.create(name: "第二政企Bu.政企事业四部",team_type: "none_tech")
Team.create(name: "第一金融Bu.保险证券事业部",team_type: "none_tech")
Team.create(name: "第一金融Bu.金融北区新业务发展部.",team_type: "none_tech")
Team.create(name: "第一金融Bu.金融北区业务一部",team_type: "none_tech")
Team.create(name: "第一金融Bu.金融华东事业部",team_type: "none_tech")
Team.create(name: "第一政企Bu.IDC业务部",team_type: "none_tech")
Team.create(name: "第一政企Bu.大企业事业部",team_type: "none_tech")
Team.create(name: "第一政企Bu.互联网北区事业部",team_type: "none_tech")
Team.create(name: "第一政企Bu.互联网东区事业部",team_type: "none_tech")
Team.create(name: "第一政企Bu.华东集成应用事业部",team_type: "none_tech")
Team.create(name: "第一政企Bu.量子拓展事业部",team_type: "none_tech")
Team.create(name: "经营管理部.经营管理部",team_type: "none_tech")
Team.create(name: "经营管理部.总经理室",team_type: "none_tech")
Team.create(name: "业务发展部.广西业务部",team_type: "none_tech")
Team.create(name: "业务发展部.军队事业部",team_type: "none_tech")
Team.create(name: "业务发展部.军工解决方案业务部",team_type: "none_tech")
Team.create(name: "业务发展部.政府公安事业部",team_type: "none_tech")
Team.create(name: "总裁室31",team_type: "none_tech")
Team.create(name: "运营商Bu.新业务事业部",team_type: "none_tech")
Team.create(name: "第一政企Bu.综合管理部",team_type: "none_tech")
Team.create(name: "运营商Bu.烟草业务部",team_type: "none_tech")
Team.create(name: "运营商Bu.综合管理部",team_type: "none_tech")
Team.create(name: "技术中心.综合管理部",team_type: "none_tech")
Team.create(name: "运营商Bu.智能制造业务部",team_type: "none_tech")
Team.create(name: "第二政企Bu.综合管理部",team_type: "none_tech")
Team.create(name: "第二金融Bu.综合管理部",team_type: "none_tech")
Team.create(name: "运营商Bu.中央区事业部",team_type: "none_tech")
Team.create(name: "第一金融Bu.综合管理部",team_type: "none_tech")
Team.create(name: "运营商Bu.铁路业务部",team_type: "none_tech")
Team.create(name: "运营商Bu.西区业务部",team_type: "none_tech")
Team.create(name: "运营商Bu.核行业业务部",team_type: "none_tech")
Team.create(name: "运营商Bu.人防业务部",team_type: "none_tech")
Team.create(name: "大客户Bu-技术综合部",team_type: "tech")
Team.create(name: "大客户Bu-公积金技术部",team_type: "tech")
Team.create(name: "大客户Bu-四川技术部",team_type: "tech")
Team.create(name: "大客户Bu-中央区技术部",team_type: "tech")
Team.create(name: "大客户Bu-云南技术部",team_type: "tech")
Team.create(name: "大客户Bu-贵州技术部",team_type: "tech")
Team.create(name: "大客户Bu-广东技术部",team_type: "tech")
Team.create(name: "大客户Bu-辽宁技术部",team_type: "tech")
Team.create(name: "大客户Bu-吉林技术部",team_type: "tech")
Team.create(name: "大客户Bu-北方区技术部",team_type: "tech")
Team.create(name: "大客户Bu-江西业务技术部",team_type: "tech")
Team.create(name: "大客户Bu-西藏技术部",team_type: "tech")
Team.create(name: "大客户Bu-湖南技术部",team_type: "tech")
Team.create(name: "大客户Bu-中央区业务三部技术部",team_type: "tech")
Team.create(name: "第二金融Bu-技术部",team_type: "tech")
Team.create(name: "第二政企Bu-技术综合部",team_type: "tech")
Team.create(name: "第二政企Bu-电力南区技术部",team_type: "tech")
Team.create(name: "第二政企Bu-电力北区技术二部",team_type: "tech")
Team.create(name: "第二政企Bu-电力北区技术一部",team_type: "tech")
Team.create(name: "第二政企Bu-电力华东上海技术部",team_type: "tech")
Team.create(name: "第二政企Bu-电力华东浙江技术部",team_type: "tech")
Team.create(name: "第二政企Bu-能源技术二部",team_type: "tech")
Team.create(name: "第二政企Bu-政企四技术支持部",team_type: "tech")
Team.create(name: "第一金融Bu-基础架构部",team_type: "tech")
Team.create(name: "第一金融Bu-北区技术二部",team_type: "tech")
Team.create(name: "第一金融Bu-华东技术部",team_type: "tech")
Team.create(name: "第一金融Bu-北区技术一部",team_type: "tech")
Team.create(name: "第一政企Bu-华东技术部",team_type: "tech")
Team.create(name: "第一政企Bu-公共池",team_type: "tech")
Team.create(name: "第一政企Bu-东区互联网技术部",team_type: "tech")
Team.create(name: "第一政企Bu-北区互联网技术部",team_type: "tech")
Team.create(name: "第一政企Bu-IDC技术部",team_type: "tech")
Team.create(name: "第一政企Bu-大企业事业部技术部",team_type: "tech")
Team.create(name: "第一政企Bu-量子技术部",team_type: "tech")
Team.create(name: "业务发展部-军工解决方案技术部",team_type: "tech")
Team.create(name: "业务发展部-广西业务部技术部",team_type: "tech")
Team.create(name: "业务发展部-政府公安事业部济南技术部",team_type: "tech")
Team.create(name: "运营商Bu-技术综合管理部",team_type: "tech")
Team.create(name: "运营商Bu-安全技术部",team_type: "tech")
Team.create(name: "运营商Bu-西区政企技术部",team_type: "tech")
Team.create(name: "运营商Bu-联通总部技术部",team_type: "tech")
Team.create(name: "运营商Bu集成交付部-智能制造",team_type: "tech")
Team.create(name: "运营商Bu-政企一部技术部",team_type: "tech")
Team.create(name: "运营商Bu集成交付部-新业务部",team_type: "tech")
Team.create(name: "运营商Bu集成交付部-业务拓展二部",team_type: "tech")

puts 'team created!!'



